var name= "Lucho Heguy"
var age=23
var gender="mujer"
var ismember= "SI"
var thirsty="si"
var drinkName="Cunnington light"
var person=prompt("hola como te llamas",name)
var person=prompt("cuantos años tenes",age)
var person=prompt("cual es tu genero",gender)
var person=prompt("sos miembro",ismember)
var person=prompt("tenes sed",thirsty)
var person=prompt("que bebida queres",drinkName)
